"""add avatar and banner public ids

Revision ID: 1da719f67f9f
Revises: d83092189af6
Create Date: 2026-06-27 15:12:01.956094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da719f67f9f'
down_revision: Union[str, Sequence[str], None] = 'd83092189af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_public_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('banner_public_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banner_public_id')
    op.drop_column('users', 'avatar_public_id')
    # ### end Alembic commands ###
